const projects = [
    {
      projectName: "E-Store",
      description: "An online marketplace for buying and selling various products.",
      image: "https://example.com/estore.jpg",
      liveLink: "https://estore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "B2B Solutions",
      description: "A suite of software tools for businesses to streamline their operations.",
      image: "https://example.com/b2b-solutions.jpg",
      liveLink: "https://b2b.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Art Gallery",
      description: "A platform for artists to showcase and sell their artwork online.",
      image: "https://example.com/art-gallery.jpg",
      liveLink: "https://artgallery.example.com",
      category: "b2c",
    },
    {
      projectName: "Marketplace App",
      description: "A mobile app that connects local sellers with buyers in their area.",
      image: "https://example.com/marketplace-app.jpg",
      liveLink: "https://marketplace.example.com/app",
      category: "b2c",
    },
    {
      projectName: "Business Analytics Tool",
      description: "A data analytics platform tailored for business decision-makers.",
      image: "https://example.com/analytics-tool.jpg",
      liveLink: "https://analytics.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Bookstore",
      description: "An e-commerce platform exclusively for books and literature.",
      image: "https://example.com/bookstore.jpg",
      liveLink: "https://bookstore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Travel Booking Website",
      description: "A website for booking flights, hotels, and vacation packages.",
      image: "https://example.com/travel-booking.jpg",
      liveLink: "https://travel.example.com",
      category: "e-commerce",
    },
    {
      projectName: "B2C Fitness App",
      description: "A fitness app that offers workouts and nutrition guidance for individuals.",
      image: "https://example.com/fitness-app.jpg",
      liveLink: "https://fitness.example.com/app",
      category: "b2c",
    },
    {
      projectName: "Supply Chain Management",
      description: "A comprehensive solution for businesses to manage their supply chains efficiently.",
      image: "https://example.com/supply-chain.jpg",
      liveLink: "https://supplychain.example.com",
      category: "b2b",
    },
    {
      projectName: "Fashion E-Commerce",
      description: "An online store specializing in fashion and clothing items.",
      image: "https://example.com/fashion-store.jpg",
      liveLink: "https://fashionstore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Event Ticketing Platform",
      description: "A platform for buying and selling tickets for concerts, sports events, and more.",
      image: "https://example.com/event-tickets.jpg",
      liveLink: "https://tickets.example.com",
      category: "b2c",
    },
    {
      projectName: "B2B Marketing Software",
      description: "A marketing automation tool designed for B2B companies.",
      image: "https://example.com/marketing-software.jpg",
      liveLink: "https://marketing.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Food Delivery",
      description: "A food delivery service connecting customers with local restaurants.",
      image: "https://example.com/food-delivery.jpg",
      liveLink: "https://fooddelivery.example.com",
      category: "b2c",
    },
    {
      projectName: "B2B CRM System",
      description: "A customer relationship management system tailored for B2B sales teams.",
      image: "https://example.com/crm-system.jpg",
      liveLink: "https://crm.example.com",
      category: "b2b",
    },
    {
      projectName: "E-Learning Platform",
      description: "An online platform for courses, tutorials, and educational content.",
      image: "https://example.com/elearning.jpg",
      liveLink: "https://elearning.example.com",
      category: "b2c",
    },
    {
      projectName: "B2B Inventory Management",
      description: "A system to help businesses efficiently manage their inventory.",
      image: "https://example.com/inventory-management.jpg",
      liveLink: "https://inventory.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Electronics Store",
      description: "An e-commerce store specializing in electronics and gadgets.",
      image: "https://example.com/electronics-store.jpg",
      liveLink: "https://electronics.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Travel Booking App",
      description: "A mobile app for booking flights, hotels, and travel experiences.",
      image: "https://example.com/travel-app.jpg",
      liveLink: "https://travel.example.com/app",
      category: "b2c",
    },
    {
      projectName: "B2B Financial Software",
      description: "Financial management software designed for B2B financial institutions.",
      image: "https://example.com/financial-software.jpg",
      liveLink: "https://financial.example.com",
      category: "b2b",
    },
    {
      projectName: "Home Decor E-Shop",
      description: "An online store offering a wide range of home decor products.",
      image: "https://example.com/homedecor.jpg",
      liveLink: "https://homedecor.example.com",
      category: "e-commerce",
    }
  ];