 export const allProjects = [
    {
      projectName: "E-Store",
      description: "An online marketplace for buying and selling various products.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://estore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "B2B Solutions",
      description: "A suite of software tools for businesses to streamline their operations.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://b2b.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Art Gallery",
      description: "A platform for artists to showcase and sell their artwork online.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://artgallery.example.com",
      category: "featured",
    },
    {
      projectName: "Marketplace App",
      description: "A mobile app that connects local sellers with buyers in their area.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://marketplace.example.com/app",
      category: "b2c",
    },
    {
      projectName: "Business Analytics Tool",
      description: "A data analytics platform tailored for business decision-makers.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://analytics.example.com",
      category: "featured",
    },
    {
      projectName: "Online Bookstore",
      description: "An e-commerce platform exclusively for books and literature.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://bookstore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Travel Booking Website",
      description: "A website for booking flights, hotels, and vacation packages.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://travel.example.com",
      category: "e-commerce",
    },
    {
      projectName: "B2C Fitness App",
      description: "A fitness app that offers workouts and nutrition guidance for individuals.",
      image: "https://blogimages.softwaresuggest.com/blog/wp-content/uploads/2018/02/08190510/Generate-More-Revenue-Using-Project-Management-Software.jpg",
      liveLink: "https://fitness.example.com/app",
      category: "b2c",
    },
    {
      projectName: "Supply Chain Management",
      description: "A comprehensive solution for businesses to manage their supply chains efficiently.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://supplychain.example.com",
      category: "b2b",
    },
    {
      projectName: "Fashion E-Commerce",
      description: "An online store specializing in fashion and clothing items.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://fashionstore.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Event Ticketing Platform",
      description: "A platform for buying and selling tickets for concerts, sports events, and more.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://tickets.example.com",
      category: "featured",
    },
    {
      projectName: "B2B Marketing Software",
      description: "A marketing automation tool designed for B2B companies.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://marketing.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Food Delivery",
      description: "A food delivery service connecting customers with local restaurants.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://fooddelivery.example.com",
      category: "b2c",
    },
    {
      projectName: "B2B CRM System",
      description: "A customer relationship management system tailored for B2B sales teams.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://crm.example.com",
      category: "b2b",
    },
    {
      projectName: "E-Learning Platform",
      description: "An online platform for courses, tutorials, and educational content.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://elearning.example.com",
      category: "b2c",
    },
    {
      projectName: "B2B Inventory Management",
      description: "A system to help businesses efficiently manage their inventory.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://inventory.example.com",
      category: "b2b",
    },
    {
      projectName: "Online Electronics Store",
      description: "An e-commerce store specializing in electronics and gadgets.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://electronics.example.com",
      category: "e-commerce",
    },
    {
      projectName: "Travel Booking App",
      description: "A mobile app for booking flights, hotels, and travel experiences.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      category: "b2c",
    },
    {
      projectName: "B2B Financial Software",
      description: "Financial management software designed for B2B financial institutions.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://financial.example.com",
      category: "b2b",
    },
    {
      projectName: "Home Decor E-Shop",
      description: "An online store offering a wide range of home decor products.",
      image: "https://assets.asana.biz/transform/d2ffb5c8-a7c2-4e39-8447-f8e2501c5bdc/article-project-planning-project-design-2x",
      liveLink: "https://homedecor.example.com",
      category: "e-commerce",
    }
  ];